-- 0038_embedding_dim_512.sql — STAGING-EMBEDDER dimension decision.
--
-- Titan Text Embeddings V2 emits 1024 dims by default and also supports 512/256. We
-- standardise on 512 (the EMBED_DIM default): it HALVES vector storage and ANN-index
-- RAM versus 1024, which matters on a t4g.small (2GB shared with Postgres), with
-- negligible retrieval-quality loss on Titan-v2. Storage/RAM at 170 users, 1000
-- notes/user: raw vectors ~340MB @ 512 vs ~680MB @ 1024 — but the pgvector ANN index
-- keeps its own copy plus graph links, so the real resident WORKING SET is ~2x:
-- ~680MB @ 512, ~1.4GB @ 1024, and it must sit alongside Postgres + shared buffers.
-- Hence 512 dims AND a db.t4g.medium (4GB) target for real load (see db_instance_class).
--
-- Every existing embedding was produced by the STUB embedder (semantically
-- meaningless) and is 1024-dim, so we simply drop and re-add the column at 512 — real
-- content re-embeds with Titan-512 going forward. PRE-FIX CONTENT IS UNSEARCHABLE until
-- re-embedded (there is no real content yet; QA data is torn down each run). No ANN
-- index exists on the column, so there is none to drop.
--
-- The column dimension MUST match config.embedDim; changing EMBED_DIM later needs a
-- new migration here plus a full re-embed.
ALTER TABLE notes DROP COLUMN IF EXISTS embedding;
ALTER TABLE notes ADD COLUMN embedding vector(512);
