import { test, expect } from '@playwright/test';

// [P0-5] Browser-level proof of the PWA shell. Runs against the built + previewed
// app (the service worker is only generated by `vite build`). Run: npm run test:e2e

test('registers and activates a service worker', async ({ page }) => {
  await page.goto('/');
  const active = await page.evaluate(async () => {
    const reg = await navigator.serviceWorker.ready;
    return Boolean(reg.active);
  });
  expect(active).toBe(true);
});

test('links a web manifest (installability prerequisite)', async ({ page }) => {
  await page.goto('/');
  const href = await page.getAttribute('link[rel="manifest"]', 'href');
  expect(href).toBeTruthy();
});

test('app shell still renders offline (no blank page)', async ({ page, context }) => {
  await page.goto('/');
  // Let the service worker install and precache the shell.
  await page.evaluate(() => navigator.serviceWorker.ready);
  await page.waitForTimeout(1500);

  await context.setOffline(true);
  await page.reload();

  // The cached shell renders the login screen even with no network.
  await expect(page.getByRole('heading', { name: 'Tovira' })).toBeVisible();
});
